Dataset:
    data_dir: '/home/vbpo-101386/Desktop/TuNIT/Datasets/Text Recognition/IIIT5K'
    annotation_dir: null
    data_info:
        data_type: 'filename'
        character: &char './configs/data/china.names'
        max_string_length: &max_length 50
        color_space: 'rgb'
        sensitive: False
        check_data: False
        load_memory: False
    data_normalizer:
        norm_type: 'sub_divide'
        norm_mean: null
        norm_std: null
        norm_resize_with_pad: True
        norm_padding_mode: 'constant'
        norm_padding_color: [255, 255, 255]
    data_augmentation:
        train:
            # - RandomRotate:
            #     angle_range: 15
            #     padding_color: 255
            #     keep_shape: False
            # - RandomGaussianBlur:
            #     sigma_range: [0.4, 0.8]
            # - RandomBrightness:
            #     delta_range: 150
            # - RandomErodeDilate:
            #     kernel_size: [3, 3]
            # - RandomSaltAndPepper:
            #     phi_range: 0.1
            # - RandomSharpen:
            #     lightness_range: [0.75, 2.0]
            #     alpha_range: 0.1
        valid:
            # - RandomRotate:
            #     angle_range: 15
            #     padding_color: 255
            #     keep_shape: False
            # - RandomBrightness:
            #     delta_range: 100
        test:
    data_loader_mode: 0

Model:
    input_shape: [32, 128, 3]
    weight_path: null
    load_weight_type: null
    Architecture:
        name: ABINet
        embed_dim: 512
        num_heads: 8
        out_dim: 2048
        loop_iters: 3
        encoder_layers: 3
        decoder_layers: 4
        max_length: *max_length
        blank_index: &blank_index 0
        drop_rate: 0.1
    Backbone:
        name: ResNet34
        num_blocks: [3, 4, 6, 6, 3]
    LabelConverter:
        name: OnehotLabelConverter
        character: *char
        batch_max_length: *max_length
        blank_index: *blank_index
    TransformLayer:
        # name: TPS_SpatialTransformerNetwork
        # F: 10
        
Train:
    # mode: 'eager'
    mode: 'graph'
    save_weight_path: &save_weight './saved_weights/'
    save_weight_type: &save_type 'tf'
    batch_size: 32
    epoch:
        start: 0
        end: 1000
        
Losses:
    - CascadeCrossentropy:
        coeff: 1

Optimizer:
    name: Adam
    beta_1: 0.9
    beta_2: 0.999
    learning_rate: 0.0001
    global_clipnorm: 20.0

Metrics:
    - EntropyCharAccuracy:
    - EntropyWordAccuracy:

Callbacks:
    - MetricHistory:
        save_best: True
        save_format: *save_type
    - LossHistory:
        save_best: False
        save_format: *save_type
    - ModelCheckpoint:
        extend_path: 'weights/checkpoint_{epoch:04d}/saved_str_weights'
        monitor: 'val_loss'
        save_weights_only: True
        save_freq: 'epoch'
        period: 100
        verbose: 1
    - TensorBoard:
        extend_path: 'logs'
        update_freq: 1
    - CSVLogger:
        extend_path: 'summary/train_history.csv'
        separator: ","
        append: True
    - TrainLogger:
        extend_path: 'logs/training_log.log'
    - TrainSummary:
        extend_path: 'summary/train_summary.txt'

Test:
    data: '/home/vbpo-101386/Desktop/TuNIT/Datasets/Text Recognition/IIIT5K/test'